version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "chore"
      include: "scope"
    groups:
      spring:
        patterns:
          - "org.springframework.boot:spring-boot-starter-parent"
          - "org.springframework.*"
      maven:
        patterns:
          - "org.apache.maven.plugins:*"
      test-dependencies:
        patterns:
          - "junit:*"
          - "org.junit*"
          - "org.mockito:*"
          - "org.assertj:*"
    labels:
      - "dependencies"
      - "java"
    assignees:
      - "pse-wtag"
      - "pgo-wtag"
      - "agm-wtag"


  - package-ecosystem: "docker-compose"
    directory: "/infra"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 3
    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - "dependencies"
      - "docker"

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"
