### Server Configuration ###
server.port=8080
server.tomcat.connection-timeout=20000
server.tomcat.keep-alive-timeout=15000
server.tomcat.max-keep-alive-requests=100
server.tomcat.accept-count=100
server.compression.enabled=true
server.compression.mime-types=application/json,application/xml,text/xml,text/plain
server.compression.min-response-size=1024


### Spring Configuration ###
spring.mvc.apiversion.use.header=X-API-Version
spring.application.name=MonolithArchitecture
spring.profiles.active=@spring.profiles.active@
spring.threads.virtual.enabled=true
spring.jpa.open-in-view=false
spring.datasource.hikari.auto-commit=false
spring.main.lazy-initialization=true
spring.jackson.default-property-inclusion=non_null

### Spring Security Configuration ###
spring.security.filter.dispatcher-types=async, error, request
spring.security.oauth2.client.provider.monolith-keycloak.issuer-uri=${WELLDEV.KEYCLOAK.ISSUER-URI}
spring.security.oauth2.client.registration.keycloak.provider=${WELLDEV.KEYCLOAK.REALM}
spring.security.oauth2.client.registration.keycloak.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.keycloak.client-id=${WELLDEV.KEYCLOAK.CLIENT-ID}
spring.security.oauth2.client.registration.keycloak.client-secret=${WELLDEV.KEYCLOAK.CLIENT-SECRET}
spring.security.oauth2.client.registration.keycloak.scope[0]=openid
spring.security.oauth2.client.registration.keycloak.scope[1]=profile
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${WELLDEV.RESOURCESERVER.JWT.SET.URI}
spring.security.oauth2.resourceserver.jwt.issuer-uri=${WELLDEV.RESOURCESERVER.JWT.ISSUER.URI}


### Keycloak Configuration ###
application.keycloak.server-url=${WELLDEV.KEYCLOAK.SERVER.URL}
application.keycloak.realm=${WELLDEV.KEYCLOAK.REALM}
application.keycloak.client-id=${WELLDEV.KEYCLOAK.CLIENT-ID}
application.keycloak.client-secret=${WELLDEV.KEYCLOAK.CLIENT-SECRET}

### Actuator Configuration ###
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=when_authorized
management.endpoint.health.probes.enabled=true