<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>mu.welldev</groupId>
        <artifactId>spring-modular-monolith-starter</artifactId>
        <version>1.0-SNAPSHOT</version>
    </parent>

    <groupId>mu.welldev.rest</groupId>
    <artifactId>rest</artifactId>

    <dependencies>
        <dependency>
            <groupId>mu.welldev.service</groupId>
            <artifactId>service</artifactId>
            <version>1.0-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <!-- Test -->
        <dependency>
            <groupId>com.tngtech.archunit</groupId>
            <artifactId>archunit</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-testcontainers</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-jpa-test</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.github.dasniko</groupId>
            <artifactId>testcontainers-keycloak</artifactId>
        </dependency>
        <dependency>
            <groupId>org.testcontainers</groupId>
            <artifactId>mysql</artifactId>
        </dependency>
        <dependency>
            <groupId>org.testcontainers</groupId>
            <artifactId>postgresql</artifactId>
        </dependency>
        <dependency>
            <groupId>org.testcontainers</groupId>
            <artifactId>junit-jupiter</artifactId>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <configuration>
                    <skip>false</skip>
                    <mainClass>${app.main.class}</mainClass>
                    <image>
                        <builder>paketobuildpacks/builder-jammy-base:latest</builder>
                        <env>
                            <BP_JVM_VERSION>25</BP_JVM_VERSION>
                            <BP_OCI_TITLE>${project.name}</BP_OCI_TITLE>
                            <BP_OCI_DESCRIPTION>${project.description}</BP_OCI_DESCRIPTION>
                            <BP_OCI_SOURCE>${project.scm.url}</BP_OCI_SOURCE>
                            <BP_OCI_VERSION>${project.version}</BP_OCI_VERSION>
                            <BP_OCI_AUTHORS>@welldev-junior</BP_OCI_AUTHORS>
                        </env>
                        <buildpacks>
                            <buildpack>docker.io/paketobuildpacks/adoptium</buildpack>
                            <buildpack>urn:cnb:builder:paketo-buildpacks/java</buildpack>
                        </buildpacks>
                    </image>
                </configuration>
                <executions>
                    <execution>
                        <goals>
                            <goal>repackage</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <!-- Enforcer -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-enforcer-plugin</artifactId>
                <configuration>
                    <rules>
                        <!-- .mvn and wrapper file must exist -->
                        <requireFilesExist>
                            <files>
                                <file>${project.parent.basedir}/.mvn</file>
                                <file>${project.parent.basedir}/.mvn/wrapper/maven-wrapper.properties</file>
                                <file>${project.parent.basedir}/mvnw</file>
                                <file>${project.parent.basedir}/mvnw.cmd</file>
                            </files>
                        </requireFilesExist>
                    </rules>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
