### USER
POST {{host}}/api/v1/auth/register
Content-Type: application/json
X-API-VERSION: 1.0

{
  "firstName": "Test",
  "lastName": "Testing",
  "age": 21,
  "gender": "MALE",
  "email": "test1@test.com",
  "username": "test1234",
  "password": "password1234"
}
> {%
    client.global.set("access_token", response.body.accessToken)
    client.global.set("refresh_token", response.body.refreshToken)
%}

###